### ISSUE TITLE
Styling and extra documentation about the gem

### ISSUE THREAD

**Issue by igakigongo** [shjang7/reddit#3]
1. Kindly add some extra styling to make the application a little bit more appealing to the users, maybe it will become an extra addition to your professional portfolio.

2. Is there extra documentation about the custom gem that you created? I think visitors are more interested in what's unique about your app. The gem might be the crucial thing here.

Otherwise cheers ....!!

**Comment by shjang7** [comment]
@igakigongo Thanks for your advice,
It is not my custom gem, https://rubygems.org/search?utf8=%E2%9C%93&query=acts_as_votable
It is useful to use for voting system.
